name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: lint
      run: bun run --run lint

    - name: build
      run: bun run --run build

    - name: Test
      run: bun run --run coverage

    - name: 'Report Coverage'
      if: ${{ !cancelled() }}
      uses:  davelosert/vitest-coverage-report-action@v2